### ISSUE TITLE
Use readr::type_convert

### ISSUE THREAD

**Issue by hadley** [tidyverse/rvest#107]
And expose `col_types` argument

**Comment by cjyetman** [comment]
Please also expose the `na` argument of `readr::type_convert` (or the `na.strings` argument of `utils::type.convert`) so that one can correctly parse a table that includes a legitimate "NA" string, e.g.
```
html_string <- 
"<table>
<tr><td>MM</td><td>Myanmar</td></tr>
<tr><td>NA</td><td>Namibia</td></tr>
<tr><td>NR</td><td>Nauru</td></tr>
</table"

rvest::minimal_html(html_string) %>% 
  rvest::html_node("table") %>% 
  rvest::html_table()
#     X1      X2
# 1   MM Myanmar
# 2 <NA> Namibia
# 3   NR   Nauru
```

**Comment by hadley** [comment]
I decided it was too much work for relatively little gain to use readr here, so I just added the `na.strings` argument.
