### ISSUE TITLE
Solaris error

### ISSUE THREAD

**Issue by jeroen** [tidyverse/rvest#108]
The unit test fails on Solaris because some of the `&nbsp;` characters turn into `"\xc2"` instead of `"\u00A0"`. This then triggers what seems to be a bug in R:

``` r
x <- c("\u00A0TEST","\xc2")
y <- c("\u00A0","\xc2")
type.convert(x, as.is = TRUE)
type.convert(y, as.is = TRUE)
type.convert(x[2], as.is = TRUE)
```

**Comment by hadley** [comment]
(4 years later) Seems to be ok now: https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/rvest-00check.html 🤷‍♂️
