### ISSUE TITLE
set_values cannot modify input checkboxes

### ISSUE THREAD

**Issue by dbuijs** [tidyverse/rvest#127]
In looking at the code for the `set_values` function, it doesn't seem to be able to handle changing the checked attribute of input checkboxes. It also doesn't throw any errors if you try to change the value of an input checkbox. 

Short-term, an error message in the `set_values` function would be helpful if you try to change the value of a checkbox.

Medium-term,  a method to change the checked attribute of input checkboxes in this function.

A related issue, which might just be sloppy coding, the search form I'm working with hasn't given unique names to each checkbox, they put the identifier in the value field. An error message or an iterator for cases where each field doesn't have a unique name would be helpful.  

An example of an html form with checkboxes where the unique identifier is in the value field and not the name (possibly out of scope for `rvest` to address):

```
hcsearchurl <- "http://www.healthycanadians.gc.ca/recall-alert-rappel-avis/search-recherche/advanced-avancee/"
hcform <- read_html(hcsearchurl) %>% html_node("form") %>% html_form()
```

**Comment by juba** [comment]
I'm facing the same problem. `set_values` modify the `value` attribute, not the `checked` one.

As a workaround, you can manually change this attribute before submitting the form with :

```r
form$fields[["checkbox_name"]]$checked <- NULL        # to uncheck
form$fields[["checkbox_name"]]$checked <- "checked"   # to check
```

**Comment by juba** [comment]
As a workaround, it seems you can "uncheck" a checkbox by assigning it a `NULL` value :

```r
form <- set_values(form, checkbox_name = NULL)
```

**Comment by etabeta78** [comment]
I stumbled upon a similar problem last week, and I cooked up a solution that worked in all the cases I tried, by modifying the rvest set_value and submit_form (submit_request, in fact) functions so that they fill and acknowledge the "checked" field of the submission form options.

Pull request #132 contains my proposed fix, which also handles properly forms with multiple checkboxes sharing the same name.
