### ISSUE TITLE
Shouldn't html_table work on tbody as well?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/rvest#140]
It seems the logic applied in `html_table` works perfectly fine on `tbody` objects as well as `table` objects.

This is convenient for, e.g., scraping the table on this page, for which the `table` object is a huge unwieldy mess, but the `tbody` object contains all the key information:

http://www.hockeydb.com/ihdb/stats/leagues/seasons/nhl19271918.html

**Comment by bsekiewicz** [comment]
I think, that this is problem with doubled (and more) rows in thead (with merging cells??)

For this table html_table() does not work
https://www.analizy.pl/fundusze/fundusze-inwestycyjne/notowania?utm_source=analizy.pl&utm_medium=MenuButton&utm_campaign=Analizy_2015_Notowania_FI)

For this table it works fine, but there is no differences between thead, tbody and tfoot
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_tbody

**Comment by hadley** [comment]
I'd say working directly with table components is currently out of scope for rvest.
