### ISSUE TITLE
Forms with no url are not supported

### ISSUE THREAD

**Issue by antoine-lizee** [tidyverse/rvest#141]
If a form comes back with no "url" specified (as it happens extremely often), the form element as a `NULL` value for the field. This lead to crashes when submitting the form, I believe because this line https://github.com/hadley/rvest/blob/7d65d84e013b1bb3827ae0a2e05ddaed4875c112/R/form.R#L303 should accomodate for NULL values. (e.g. `url <- ifelse(is.null(form$url), "", form$url)`).

REPEX:

```
session <- html_session('http://thinklab.com/login')
sign_in_form <<- html_form(session)[[3]]
session %>% submit_form(sign_in_form)
```

Using something like `sign_in_form$url <- ""` made it work.

**Comment by hadley** [comment]
If the form doesn't specify an `action` how is rvest supposed to know where to submit the data?
