### ISSUE TITLE
Is use of sessions necessary for submit_form()?

### ISSUE THREAD

**Issue by petermeissner** [tidyverse/rvest#147]
I really love rvest - its such a nice interface, sooo efficient, easy to use, .... `praise::praise()`

That being said, I had a try with rvest's form parsing and submitting workflow and was kind of confused that it requires to use sessions. Since rvest keeps track of cookies, referer and the like anyways it seems alien to me to demand the usage of sessions.

I had a look at the code and as far as I understand, the session is only really needed to convert relative URLs to absolute URLs to submit the form to the right location. 
- Could this not be inferred from the last  request as are things like referer and cookies? 
- Or would it be possible to allow for an extra function parameter that than turns of the usage of sessions?

**Comment by hadley** [comment]
How would rvest know what the "last request" is? You'd either need to thread it through via the form object (complicated, and easily broken) or pass it in as another parameter, in which case it's no better than a session object.
