### ISSUE TITLE
handle multiple submit fields with same name

### ISSUE THREAD

**Issue by petermeissner** [tidyverse/rvest#156]
I had the following problem:

A form had **multiple submit buttons all with the same name but different values**. Because submit_form() only allows for selection of the submit by name I could not use it.

So it would be nice to be able - in addition to name 
- select submit buttons by index

or to be able to 
- manually control 

what is used for the submit.

(originally submitted as pull request issue #146; for an real life example go here http://dipbt.bundestag.de/dip21.web/bt , click on Beratungsabäufe on the left side and have a look at the buttons)

**Comment by xguardi** [comment]
Any progress? This is a failry common pattern when parsing paginated results (pagination link sometimes are different submits with the same name but different valuers.
As in :
<form> 'formPag' (POST http://www.xxxx.xxx)
  <input hidden> 'type': 1
  <input submit> 'pag': 2
  <input submit> 'pag': 3
  <input submit> 'pag': 4
Cheers!

**Comment by xguardi** [comment]
Just in case somebody has this problem (several submit fields with the same name but different value). For example something like:

```
<div align="center" class="pagination-nums">
  <input type="submit" name="pag" value="1">
  <span class="pagination-act">2</span>
  <input type="submit" name="pag" value="3">
  <input type="submit" name="pag" value="4">
</div>
```

The way I finally solved was by using Hadley's httr library (which rvest is build upon). It's lower level but actually very easy to use. For the case above it would be:

  ```
library(httr)
library(xml2)

 # form fields 
 fields <- list(
      'pag' = 2
  )
 # post request
 r <- POST(url, 
            body = fields, 
            encode = 'form',
            user_agent('libcurl/7.43.0 r-curl/0.9.7 httr/1.2.1'))
 # read as xml
 r <- xml2::read_html(r)
```

Cheers!
