### ISSUE TITLE
Excluding rows/nodes to help html_table

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/rvest#164]
Related to [this](http://ja.stackoverflow.com/questions/28261/) (Japanese-language) SO question.

I want to read the main table on this page:

http://www.data.jma.go.jp/obd/stats/etrn/view/daily_s1.php?prec_no=44&block_no=47662&year=2016&month=7&day=&view=

As you can see, the header is complicated -- lots of multi-rows and multi-columns. 

We can get the table itself just fine in XML:

```
URL <-
  paste0("http://www.data.jma.go.jp/obd/stats/etrn/view/",
         "daily_s1.php?prec_no=44&block_no=47662&year=2016",
         "&month=7&day=&view=")
tbl <- read_html(URL) %>% 
  html_node(xpath='//*[@id="tablefix1"]')
```

And printing `tbl` suggests it consists of a "vector" which we can subset:

```
print(tbl)
# {xml_node}
# <table>
#  [1] <tr class="mtx">\n  <th rowspan="4" scope="col">日</th>\n  <th colspan ...
#  [2] <tr class="mtx" scope="colgroup">\n  <th scope="colgroup">現地</th>\n   ...
#  [3] <tr class="mtx">\n  <th rowspan="2" scope="col">平均</th>\n  <th rowspa ...
#  [4] <tr class="mtx">\n  <th scope="col">1時間</th>\n  <th scope="col">10分間< ...
#  [5] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
#  [6] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
#  [7] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
#  [8] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
#  [9] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [10] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [11] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [12] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [13] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [14] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [15] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [16] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [17] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [18] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [19] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# [20] <tr class="mtx" style="text-align:right;">\n  <td style="white-space: ...
# ...
```

It would be great to just exclude a subset of the nodes that we determine belong to the table header, but (despite being printed as if they can, with `[1]`, `[2]`, etc.) we _cannot_ index this object as we might expect we could given the output of `print(tbl)`:

```
tbl[-1L]
# $doc
# <pointer: 0x6bb46c0>
```

`fill = TRUE` _does_ work, eventually, to getting this table into a format ready to be manipulated.

But it seems like wasted effort. Why not just tell `html_table` to exclude the first 4 rows? Or exclude those cells ourselves from the XML object?

**Comment by kmace** [comment]
I have this issue too, in my case some tables are empty and so it throws an error half way through.

**Comment by hadley** [comment]
This is actually an xml2 issue, since it's xml2 that provides the `xml_node` class. If you're still interested in this problem, I'd recommend creating a reprex over at xml2.
