### ISSUE TITLE
Failed set_value with input name having []

### ISSUE THREAD

**Issue by hemans** [tidyverse/rvest#167]
I am having a problem setting values to an input name with square brackets eg. 
`<input text> 'user_session[email]':`
  `<input password> 'user_session[password]':`

Error looks like this:
`Error: unexpected '=' in "form <- set_values(login, user_session[email]="`

Grateful if I could get some help ...

Many thanks

**Comment by hadley** [comment]
You need `` ` ``:

```R
form <- set_values(login, `user_session[email]` = 10
```
