### ISSUE TITLE
Peer certificate cannot be authenticated with known CA certificates

### ISSUE THREAD

**Issue by iProcrastinate** [tidyverse/rvest#169]
When trying to webscrape from a UK government website (https://www.evidence.nhs.uk/formulary/bnf/current) the html_session() command returned the above error. In this instance I could communicate with the server over plain http but if I needed to use https address there does not seem to be any way of either pointing to a certificate file or overriding the warning and trusting the site anyway (which seems reasonable when using a government site and non-sensitive data). Sorry if I have missed this in the documentation.

**Comment by rusharp** [comment]
+1

**Comment by Alekhb** [comment]
+1

**Comment by jimhester** [comment]
The site in question seems to no longer exist (I get a 503 error with chrome), for both the http and https endpoints.

If someone has a different site with the same issue we can reopen this.

**Comment by Alekhb** [comment]
Hi Jim,

Can you look into this site :  https://www.petsupermarket.com/store_locator, this site also gives the same certificate issue?
--

**Comment by hadley** [comment]
Seems to work fine for me.
