### ISSUE TITLE
Running on Fedora 23 - missing dependency?

### ISSUE THREAD

**Issue by oNIenSis** [tidyverse/rvest#174]
To run Rvest on Fedora 23 I needed to install an old version of the ICU libraries, Rscript crashed out with error:
unable to load shared object '/usr/lib64/R/library/stringi/libs/stringi.so':
libicuuc.so.52: cannot open shared object file: No such file or directory

I had previous run it fine on an older Fedora build, but this one uses libicu54 which must not be backward compatible.  Anyway to fix I compiled a version of libicu52 from source (see https://sourceforge.net/projects/icu/files/ICU4C/52.1/), and copied the contents of ./lib/ to /usr/lib64.  Works fine after that.

**Comment by hadley** [comment]
This sounds like a stringi problem, not an rvest problem.
