### ISSUE TITLE
Should html_text handle <br> as new line char or whitespace?

### ISSUE THREAD

**Issue by ktmud** [tidyverse/rvest#175]
When the childnodes contain `<br>` tags, shouldn't `html_text()` replace `<br>` with a whitespace or new line character? Otherwise the text will be crammed, making it harder to use RegExp to further disentangle text components.

**Comment by rentrop** [comment]
+1. This would be a great enhancement.

A quick workaround would be the following:
```
require(rvest)
txt <- '<td style="vertical-align:right;text-align:right;">31.12.2009<br>EUR<br></td>
<td style="vertical-align:right;text-align:right;">31.12.2009<br>EUR<br></td>'

doc <- read_html(txt)

doc %>% 
  html_nodes("td") %>% 
  lapply(xml_nodes, xpath = "./text()") %>% 
  vapply(paste, collapse="\n", character(1))
```

Which results in:
`[1] "31.12.2009\nEUR" "31.12.2009\nEUR"`

**Comment by rentrop** [comment]
This is directly related to https://github.com/hadley/xml2/issues/152

**Comment by belg4mit** [comment]
I just got hit by this "feature" today. It definitely needs to be called out in the documentation, or a DWIM update to the functionality.

**Comment by JustGitting** [comment]
I'm also affected by this issue when using html_table(). Where a table cell contains <br>, the text that is returned is concatenated together, without a space or newline.

**Comment by vspinu** [comment]
One can use `xml_replace` or `xml_add_sibling` to modify the `<br>` element:

```R

doc <- read_html('<td>AAA<br>BBB</td><td>CCC<br>DDD</td>')
dummy <- xml_node(read_xml("<doc><span>|||</span></doc>"), "span")

xml_add_sibling(xml_nodes(doc, "br"), dummy)
xml_text(xml_nodes(doc, "td"))
## [1] "AAA|||BBB" "CCC|||DDD"
```

**Comment by ScoobyQ** [comment]
Did this ever make it in as a feature?

**Comment by hadley** [comment]
It's going to be hard to do what you mean in most situations, i.e. what happens if you call `html_text()` on a node that contains multiple paragraphs? Does the paragraph structure need to be maintained in the output? If so, does that mean that any whitespace that HTML would ignore should also be ignored? What happens if the node contains `<li>` elements? What's the general rule? Should all block elements be translated to paragraphs, `<br >` translated to `\n` and then all other whitespace is normalised using the [HTML rules](https://www.w3.org/TR/html4/struct/text.html#h-9.1)?

**Comment by belg4mit** [comment]
I think this is a case where it is 

> It's going to be hard to do what you mean in most situations, i.e. what happens if you call `html_text()` on a node that contains multiple paragraphs? Does the paragraph structure need to be maintained in the output? If so, does that mean that any whitespace that HTML would ignore should also be ignored? What happens if the node contains `<li>` elements? What's the general rule? Should all block elements be translated to paragraphs, `<br >` translated to `\n` and then all other whitespace is normalised using the [HTML rules](https://www.w3.org/TR/html4/struct/text.html#h-9.1)?

I think that is letting the perfect become the enemy of the good. If one has funky content that one wants to parse perfectly, one can always parse the content in chunks, but as the ticket history seems to indicate, often people just want a reasonably clear, complete, human readable extract. There are conventions for converting HTML to text as in email that would cover cases such as lists if that's a hangup.

**Comment by ktmud** [comment]
I think semantically it makes sense to just let `html_text` behave exactly like the DOM API `HTMLElement.innerText`, which translates `<br>` to `\n`.

**Comment by hadley** [comment]
@belg4mit no, it's a matter of figuring out how to best align people's expectations with the reality of HTML. Can you please point me to documented conventions for converting HTML to text?

@ktmud it seems like `innerText()` is a bit more complicated than just converting `<br />` to `\n`: https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute. However, that's at least a reasonable place to start and provides the convention of adding two line breaks at the end of `<p>` tags, and a single line break at the end of other block-level tags.

**Comment by belg4mit** [comment]
I don't know of any written specs, but w3c has a list of tools here: https://www.w3.org/Tools/html2things.html although it's lacking some more modern options like elinks or w3m. As the documentation for html2text notes, it is not possible to perfectly render the rich formatting of HTML down to plain text, but common stuff can be handled well.
For example, the tools I've used add newlines after blocks and turn unordered lists into:

* something
* like
* this

Ordered lists have letter or number prefixes instead. 

https://rdrr.io/cran/htm2txt/ Might be useful, although the expressions it uses need to be updated to accept XHTML syntax i.e; it handles <br> but not <br/> so

htm2txt("<p>Hello<br>World</p><p>Gah!!!!<br/>Florpus</p>")

is missing a newline before Florpus

"Hello\nWorld\n\nGah!!!!Florpus"

**Comment by hadley** [comment]
@belg4mit ok that doesn’t sound like a very fruitful avenue to pursue then. If we wanted to go in that direction, we’d just use pandoc to convert html to markdown.

**Comment by ktmud** [comment]
Isn't the innerText spec already a very much generally accepted convention (while fulfilling most use cases of rvest)? I would imagine people who use rvest for web scraping care more about generating analizable, tokenizable text (which feeds into other pieces of information extraction algorithms), rather than rendering the text to a perfect user-readable format.

**Comment by hadley** [comment]
@ktmud I’m not sure what you’re getting at. It seems like a reasonable place to start to me.
