### ISSUE TITLE
Scraping from javascript websites

### ISSUE THREAD

**Issue by higgi13425** [tidyverse/rvest#183]
An example is http://kff.org/other/state-indicator/total-residents/?currentTimeframe=0
simple table with data (one of many useful pages they share publicly), but not accessible via rvest.

It appears that there is an obscure workaround :
https://www.datacamp.com/community/tutorials/scraping-javascript-generated-data-with-r#gs.7KHOcV0
but it is not very accessible to non-coders.

Any way to make this a under-the-hood capability of rvest?

**Comment by nick-ulle** [comment]
@higgi13425 An all-R alternative to the workaround you've found is to use the RSelenium package, which allows you to control a web browser (or PhantomJS) from R. The RSelenium interface is simple but installing Selenium can sometimes be difficult.
