### ISSUE TITLE
Fatal error using rvest in 32bit windows7

### ISSUE THREAD

**Issue by wldnjs** [tidyverse/rvest#184]
Hello, I tried to load rvest, in r-studio, however got 'R Session aborted' Messages.
It seems like 64bit can deal with this problem, because of another condition, I can`t upgrade this PC to 64bit.

My code is as follow:

library(httr)
library(rvest)
T <- NULL

res <- GET('http://mayor.ep.go.kr/CmsWeb/viewPage.req?idx=PG0000003874&board_code=T001&searchFlag=&searchKeyword=&page=1&pageNum=1')
h <- read_html(res)
tbody <- html_nodes(h, 'tbody')

This code worked at R i386 3.3.2. But R-studio makes fatal error message. 

Here is my session info.

R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949   
[3] LC_MONETARY=Korean_Korea.949 LC_NUMERIC=C                
[5] LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2

My r-studio version is '0.99.489'
I really hope to find the way not to change 32-bit to 64-bit.

Thanks

**Comment by hadley** [comment]
This is likely to be an xml2 bug, because the symptoms you describe are of a crash in C code, and rvest contains no C code. If you are still have the problem, I recommend creating a reprex and filing an issue in [xml2](https://github.com/r-lib/xml2)
