### ISSUE TITLE
guess_encoding could look for <meta charset>

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/rvest#185]
Inspired by Floo0's answer [here](http://stackoverflow.com/a/41685384/3576984).

If the web page itself is making a note of the page's intended encoding, this is probably a better indicator of the encoding than what `stringi` might suggest.

**Comment by hadley** [comment]
The problem is that requires that the page already be read with a reasonable encoding, otherwise you can't use xml2 to access the `charset` meta tag.
