### ISSUE TITLE
Feature request: an "as.is" argument for rvest::html_table that returns all values as character

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/rvest#186]
I have a project with data that includes IDs that are all digits and sometimes include initial zeros.  It would be useful to turn of or delay column type determination and transform in rvest::html_table so we would have the option of treating these values faithfully as strings.  Feature request: an "as.is" argument for rvest::html_table that returns all values as character.

**Comment by hadley** [comment]
Will be solved (differently) by #107
