### ISSUE TITLE
If html_table returns a single table, coerce output to data.frame (or data_frame)

### ISSUE THREAD

**Issue by bbrewington** [tidyverse/rvest#187]
Here's an example of an html_table returning a list of length 1 which contains a single data frame.  Typically, when I'm web scraping (clean?) HTML, I aim to find the CSS selector of the table so that it returns a single table.  I realize this isn't always the case, and it may be more robust to have html_table always return a list of all the tables within the node.  Just looking to reduce the number of times I have to write `%>% .[[1]]` at the end of my pipes :)

```
result <- read_html("http://www.w3schools.com/html/html_tables.asp") %>% 
     html_nodes("#customers") %>% 
     html_table()

class(result)
[1] "list"

str(result)
List of 1
 $ :'data.frame': ...
```
This returns a `list` of length 1 containing a single `data.frame`

Maybe this feature could be available as an option in the function, like `collapse=TRUE`

**Comment by hadley** [comment]
You should be using `html_node()`:

``` r
library(rvest)
#> Loading required package: xml2

result <- read_html("http://www.w3schools.com/html/html_tables.asp") %>% 
  html_node("#customers") %>% 
  html_table()

str(result)
#> 'data.frame':    6 obs. of  3 variables:
#>  $ Company: chr  "Alfreds Futterkiste" "Centro comercial Moctezuma" "Ernst Handel" "Island Trading" ...
#>  $ Contact: chr  "Maria Anders" "Francisco Chang" "Roland Mendel" "Helen Bennett" ...
#>  $ Country: chr  "Germany" "Mexico" "Austria" "UK" ...
```

<sup>Created on 2019-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
