### ISSUE TITLE
Error in open.connection(x, "rb") : Couldn't resolve host name

### ISSUE THREAD

**Issue by litao1105** [tidyverse/rvest#188]
I want to scrap some data from web,my R version is 3.3.2 on centos6.5.
Error in open.connection(x, "rb") : Couldn't resolve host name
code:
> url='http://www.bsb.com.cn/yhk/yhkx/yhlbt/index.html'
> library(rvest)
> library(magrittr)
> url='http://www.bsb.com.cn/yhk/yhkx/yhlbt/index.html'
> url%>%read_html()%>%html_nodes('.newsList-a')%>%html_text(trim=T)
Error in open.connection(x, "rb") : Couldn't resolve host name
>

**Comment by hadley** [comment]
That typically indicates a problem with the connection between your computer and the server, and there's unfortunately nothing I can do about it.

**Comment by vivard** [comment]
I got the same error, and https://stackoverflow.com/questions/36043172/package-rvest-for-web-scraping-https-site-with-proxy/38463559#38463559 solve my issue.
