### ISSUE TITLE
read_html( ) was failed to read html data

### ISSUE THREAD

**Issue by LeslieTse** [tidyverse/rvest#194]
Using the read_html is failed to read data in website : http://zu.gz.fang.com/.
  
    library(rvest)
    gurl <- "http://zu.gz.fang.com/"
    data <- read_html(gurl,encoding="UTF-8") 
    data
    {xml_document}
    <html>
    [1] <body><p>\u008b</p></body>
 
How to solve the problem?

**Comment by xhudik** [comment]
your page is not UTF-8 ;)

this works:
```
data <- read_html(gurl,encoding="gbk") 
data
```
