### ISSUE TITLE
Avoid scraping IMDB in readme/vignettes

### ISSUE THREAD

**Issue by HBossier** [tidyverse/rvest#195]
Hello,

Bit a silly comment and possibly it has been given before (though I could not find it in the _issues_ list).
But the _Conditions of Use_ from IMDb explicitly state that:

> **Robots and Screen Scraping**: You may not use data mining, robots, screen scraping, or similar data gathering and extraction tools on this site, except with our express written consent as noted below.

Hence, unless this consent has been given, you might want to change the demo given in the README in order to stay safe...

[IMDb conditions](http://www.imdb.com/conditions)

**Comment by hadley** [comment]
This example is also used in both vignettes, so we'd need to change it there too. The question is what to change it too — ideally it should be something that is unlikely to change in the future.

**Comment by hadley** [comment]
Best bet is to create some example vignettes suitable for scraping. Can use https://scrapethissite.com/pages/ for inspiration.
