### ISSUE TITLE
Error in doc_parse_raw

### ISSUE THREAD

**Issue by hauj12123** [tidyverse/rvest#203]
Dear Author,

First, thank you for reading this post. Recently, I encountered a problem when fetching the source code of a webpage. I did a deep search in the Internet and people agreed it due to the webpage encoding problem. The webpage below is a **simplified Chinese web page** with charset encoding in **GB2312** as below. When I tried to fetch the source code and received an error

**Webpage encoding part:**
http-equiv="Content-Type" content="text/html;charset=gb2312"

**Fetch the source code but didn't work:**
source_code <- read_html("http://www.uukanshu.net/b/37133/156039.html"), or;
source_code <- read_html("http://www.uukanshu.net/b/37133/156039.html", encoding = "UTF-8"), or;
source_code <- read_html("http://www.uukanshu.net/b/37133/156039.html", encoding = "gb2312")

**Error received:**
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  input conversion failed due to input error, bytes 0xF3 0x77 0xD6 0xD0 [6003]

How can I solved this problem or bypass it? I did not find a solution online. 
It is appreciated that if any solution provided. 

Thank you.

Best regards,
Jason

**Comment by Key-Kanon** [comment]
I think you need to set the right coding format，and you can use guess_encoding to figure out what the real encoding is.
you get detailed help through input "? encoding" in R.
Hoping This Helps.

**Comment by SwimmingLateRabbit** [comment]
I have the same problem with, also, a Chinese website. I tried both guess_encoding and repair_encoding and it says "No guess has more than 50% confidence". How do I resolve this? 

Thanks a lot!

**Comment by Key-Kanon** [comment]
Using RSelenium package can bypass this problem.

**Comment by hadley** [comment]
The document appears to have encoding "GBK", which I had never heard of before. I determined this by opening in safari, and then running `document.inputEncoding` in the console.

```R
source_code <- read_html("http://www.uukanshu.net/b/37133/156039.html", encoding = "GBK")
```

**Comment by PriyaShaji** [comment]
Hey, could anyone help me with the same error but it gives the error in kable() function

<img width="904" alt="Screen Shot 2019-03-23 at 11 02 56 PM" src="https://user-images.githubusercontent.com/35895465/54874344-ddfdc980-4dbf-11e9-943f-891a16902077.png">

The error is with the tweet table.
With LinkedIn table, the code works just fine and gives the output for it.
