### ISSUE TITLE
Documentation for html_node needs clarification

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/rvest#206]
Currently in `?html_node`, we see:

> When given a list of nodes, `html_node` will always return a list of the same length

Unfortunately, this is not correct:

```
pg = read_html('<a><b>1</b></a><a>2</a>')
pg %>% html_nodes('a') %>% html_node(xpath = '//b')
# {xml_nodeset (1)}
# [1] <b>1</b>
pg %>% html_nodes('a') %>% html_node(xpath = 'b')
# {xml_nodeset (2)}
# [1] <b>1</b>
# [2] <NA>
```

This is acknowledged in the comments of the examples (_caveat_: I only noticed this just now after carefully poring over the full help page in anticipation of this issue):

```
# XPath selectors ---------------------------------------------
# chaining with XPath is a little trickier - you may need to vary
# the prefix you're using - // always selects from the root noot
# regardless of where you currently are in the doc
```

This proviso should be mentioned up front when distinguishing the use cases of `html_node`. 

FWIW, it may be worth elaborating on this neat feature of `html_node` as well, since it appears to come up nontrivially often:

- https://stackoverflow.com/q/41708685/3576984
- https://stackoverflow.com/q/47619312/3576984
- https://stackoverflow.com/q/46597294/3576984
- https://stackoverflow.com/q/42167159/3576984 [related]

(probably others)

**Comment by hadley** [comment]
I do not see that problem:

``` r
library(rvest)
#> Loading required package: xml2

x <- minimal_html('<a><b>1</b></a><a>2</a>')
x %>% html_nodes('a') %>% html_node(xpath = '//b')
#> {xml_nodeset (2)}
#> [1] <b>1</b>
#> [2] <b>1</b>
x %>% html_nodes('a') %>% html_node(xpath = 'b')
#> {xml_nodeset (2)}
#> [1] <b>1</b>
#> [2] <NA>
```

<sup>Created on 2019-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
