### ISSUE TITLE
read_html() sometime fetches data and sometimes return null

### ISSUE THREAD

**Issue by yogesh1612** [tidyverse/rvest#211]
I am trying to fetch data from tripadvisor using following code I observed that list variable ( webpage_data_n ) that i created sometime contains text and sometime it does not.

hotels_Goa <- read_html('https://www.tripadvisor.in/Hotels-g297604-Goa-Hotels.html')
# Collecting all the hotel names in Goa_Hotels
hotel_Name <- hotels_Goa %>% html_nodes('.prominent') %>% html_text() 
hotel_url = hotels_Goa  %>% 
  html_nodes('a.review_count') %>% 
  html_attr("href") %>%
  xml2::url_absolute("https://www.tripadvisor.in")

for( i in 1:5){
   webpage<-read_html(hotel_url[i])
  webpage_html_n <- html_nodes(webpage,'.reviewItemInline~ .prw_reviews_text_summary_hsx .partial_entry')
  review_title <-html_nodes(webpage,'.noQuotes')
  hotel_name <- html_nodes(webpage,'#HEADING')
  
  webpage_data_n <- html_text(webpage_html_n)
  r_t_text <- html_text(review_title)
  h_name <- html_text(hotel_name)
  
  df1 <- data.frame(Hotel_name = h_name,Review_Title=r_t_text,Review = webpage_data_n)
  View(df1)
  df2 <- rbind.fill(df2,df1)
}

**Comment by hadley** [comment]
You are probably hitting some limits placed by trip advisor.
