### ISSUE TITLE
read_html not exported by rvest, although 'html is deprecated: please use read_html() instead'

### ISSUE THREAD

**Issue by msberends** [tidyverse/rvest#214]
The man page of `rvest::html` states:

----

**Description**
`html` is deprecated: please use `read_html()` instead. 

----

But `read_html()` is not exported by `rvest`, which I didn't expect based on the description of the deprecated function.

![image](https://user-images.githubusercontent.com/31037261/37398214-0fbde554-277e-11e8-99ae-184db1633b3f.png)

Might be good idea to `@export` the `@inherit xml2::read_html` in the `rvest` package?

**Comment by jimhester** [comment]
rvest has xml2 in `Depends`, so xml2 is attached when rvest is attached.

Admittedly it makes this error message somewhat confusing, it should really be `html` is deprecated: please use `xml2::read_html()` instead.

**Comment by dmi3kno** [comment]
Why can't `rvest` just re-export it? Makes it really painful to add another ImportFrom in packages.

**Comment by hadley** [comment]
@dmi3kno my expectation is that you have to use xml2 and rvest together. I don't think importing another function from a different package is really that painful.
