### ISSUE TITLE
html_submit doesn't return the right output

### ISSUE THREAD

**Issue by MislavSag** [tidyverse/rvest#217]
I have written the code for filling and submitting the form:

```
# fill and submit form
bh <- html_session("https://www.bhtelecom.ba/index.php?id=7226&a=new", encoding = "UTF-8")
form <- html_form(bh)[[2]]
from_filled <- form %>% set_values(im = "Daniel", pr = "Horvat")
session <- submit_form(bh, from_filled)
```
The code submit the form without an error, but it doesn't return the output table I get if I submit the form manually. I get two tables:

`read_html(session) %>% html_nodes("table")`
but I should get 6 tables, and one table should contain data I need.

Simply, how can I submit form from this web site using rvest or httr packages?

**Comment by hadley** [comment]
The different is probably due to javascript, which is executed in the browser, but not by rvest. You may need to try [RSelenium](https://cran.r-project.org/web/packages/RSelenium/index.html) or similar.
