### ISSUE TITLE
set_values using input id

### ISSUE THREAD

**Issue by adam52** [tidyverse/rvest#219]
I have run into an issue where an `input` field is missing its `name` attribute. Is it possible to set the value of this field with the `set_values()` function, without referencing the `name` attribute? Using the `id` perhaps?

Thanks!

**Comment by hadley** [comment]
> If no name is specified, or name is empty, the input's value is not submitted with the form.
— https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name

So that would make rvest work differently to most web browsers.
