### ISSUE TITLE
read_html() can't read a URL containing '#'

### ISSUE THREAD

**Issue by jamjaemin** [tidyverse/rvest#228]
read_html() can't read in a URL containing '#' in its address.

I am scraping a music streaming website where new songs are updated and indexed. The 1st page is only successfully loaded by read_html function. But it doesn't work for the 2nd page and onward -- instead, the function returns the 1st page again. 

Turns out it results from the structure of the URLs. That is,

The URL of the 1st page (displaying 50 songs) is:
https://www.melon.com/genre/song_list.htm?gnrCode=GN0300

And the URL of the 2nd page (displaying 51st -100th song) just adds some string behind the first one, starting #:
https://www.melon.com/genre/song_list.htm?gnrCode=GN0300#params%5BgnrCode%5D=GN0300&params%5BdtlGnrCode%5D=&params%5BorderBy%5D=NEW&params%5BsteadyYn%5D=N&po=pageObj&startIndex=51

read_html doesn't seem to take the part beginning from '#'; so basically, it operates as if I put it the same URL of the first page again.

The 3rd page is different only in "startIndex=101", as it begins from the 101st song. read_html returns the 1st page too.

Would there be other ways around to let it identify correct URLs? Or a quick fix will be very much appreciated. Thanks.

**Comment by hadley** [comment]
This is most likely because on page javascript handles the part of the url after `#`, and because rvest simply fetches the url, the javascript is never executed. You may need to try [RSelenium](https://cran.r-project.org/web/packages/RSelenium/index.html) or similar.
