### ISSUE TITLE
Help entry for html_table (fill=TRUE) seems wrong

### ISSUE THREAD

**Issue by WHardyPL** [tidyverse/rvest#229]
Hi!
The entry for the "fill" option in html_table seems wrong. It currently states:
"If TRUE, automatically fill rows with fewer than the maximum number of columns with NAs"

However, the actual outcome is that the original value gets inserted into each of the subcells comprising the original cell that spanned more than row/column.

**Comment by jimhester** [comment]
Could you provide an example that illustrates the problem? Ideally a [reprex](https://www.tidyverse.org/help/) (reproducible example).

**Comment by WHardyPL** [comment]
Hi Jim,
I'm sorry but I'm not familiar with reprex. However, it's easy for me to provide you with a very short example:

`site <- read_html("https://en.wikipedia.org/wiki/Game_of_Thrones_(season_1)")
table <- html_table(site)[2] # gives an error "Table has inconsistent number of columns"
table <- html_table(site, fill = TRUE)[[2]]`

The error is there, because every second row in the Episodes table in the link provided has one cell that is spread across all seven columns.

According to the help file, using `fill = TRUE` should 
> automatically fill rows with fewer than the maximum number of columns with NAs.

However, clearly that's not what happens. Instead the value gets inserted to all the columns. Plus, I think this also works similarly for columns with fewer than the maximum number of rows.

So I actually think the function does a good thing, but that the help file contains a wrong description of the `fill` argument.

**Comment by hadley** [comment]
`fill = TRUE` does work as documented, as shown by this reprex:

``` r
library(rvest)
#> Loading required package: xml2
html <- minimal_html("
  <table>
    <tr><td>a</td><td>b</td></tr>
    <tr><td>a</td></tr>
  </table>
")
html_table(html, fill = TRUE)[[1]]
#>   X1   X2
#> 1  a    b
#> 2  a <NA>
```

The problem with that table is that the episode descriptions use `colspan = "8"`, so, by convention, rvest repeats the value.
