### ISSUE TITLE
timed out issues. Any ideas?

### ISSUE THREAD

**Issue by targeteer** [tidyverse/rvest#241]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# I'm trying to scrap data from this site and I keep getting timed out error
http://www.kcna.kp/kcna.user.article.retrieveNewsViewInfoList.kcmsf#this
Other sites work well, so I'm guessing its not a setup problem. Any ideas?
```

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
