### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by renkun-ken** [tidyverse/rvest#247]
The following example works when the url was `http://`. When the website forces `https://`, `html_session` no longer works with it.

```r
library(rvest)
#> Loading required package: xml2

url <- "https://www.hkexnews.hk/sdw/search/mutualmarket.aspx?t=sh"
session <- html_session(url)
#> Error in curl::curl_fetch_memory(url, handle = handle): SSL certificate problem: unable to get local issuer certificate
```

**Comment by renkun-ken** [comment]
The CA certificate seems to be problematic at the moment. But if I tell `curl` to ignore it, it should work anyway.

```r
h <- new_handle(ssl_verifypeer = FALSE)
curl::curl_fetch_memory(url, handle = h)
```

However, I don't see a way to to let `html_session` to use the `curl_handle` I created with `ssl_verifypeer = FALSE`.

**Comment by hadley** [comment]
You should be able to use `httr::with_config()` here.
