### ISSUE TITLE
html_form can't be read when trying to log in 

### ISSUE THREAD

**Issue by np2201** [tidyverse/rvest#263]
I had been using code to scrape some tables on a website that needed a log in, but now I cannot get rvest to find the form on the login page.  I assume that something changed with the website.  Is there any way to get through this with rvest or do I need to look other routes.  I saw someone posted a workaround in issue #192.  Has there been any update with that or any other way to go about it?

``` r
library(rvest)
#> Loading required package: xml2

pwcc <- "https://www.pwccmarketplace.com/login"
sesh <- html_session(pwcc)
form <- html_form(sesh)
#> Error: Current page doesn't appear to be html.
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmi3kno** [comment]
You need to point to the tag, where the form is located. This form is not at the page root
```r
library(rvest)
url <- "https://www.pwccmarketplace.com/login"

url %>% 
  html_session() %>% 
  html_node("form") %>% 
  html_form()
#> <form> '<unnamed>' (POST https://www.pwccmarketplace.com/login)
#>   <input hidden> '_token': 4VpWeTInzMvSmxMxEQL9VsSCOrETGa7k8xV1peLS
#>   <input hidden> 'redirect': 
#>   <input email> 'email': 
#>   <input password> 'password': 
#>   <input hidden> 'remember': false
#>   <input checkbox> 'remember': true
#>   <button submit> '<unnamed>
```
Please, remember to close the issue.
