### ISSUE TITLE
html() is deprecated in favor of read_html(), but only html() is listed on the Reference page of the website

### ISSUE THREAD

**Issue by jrosen48** [tidyverse/rvest#266]
`html()` is noted as being deprecated in favor of `read_html()`, but only `html()` is listed on the Reference page of the website. Would it be possibly to replace this function with `read_html()` there -- or to include both?

https://rvest.tidyverse.org/reference/index.html

**Comment by Fredo-XVII** [comment]
Not only that, `html_read()` is not exportable from rvest.  See the reprex below:

reprex from RStudio
```
  url_dates <- url("https://www.finra.org/rules-guidance/key-topics/covid-19/shelter-in-place")
  webpage <- rvest::read_html(url_dates)
#> Error: 'read_html' is not an exported object from 'namespace:rvest'
```
But this works:
```
  url_dates <- url("https://www.finra.org/rules-guidance/key-topics/covid-19/shelter-in-place")
  webpage <- read_html(url_dates)
```

**Comment by Fredo-XVII** [comment]
I also found that in the `Parse.R` file that their is no reference to `read_html`, only `html`.  Yet, the entire file talks about `read_html`.  What is confusing is that there is an `xml2::read_html` function. 

Might be an easy fix, thoughts?

```
#' # From an httr request
#' google2 <- read_html(httr::GET("http://google.com"))
html <- function(x, ..., encoding = "") {
  .Deprecated("xml2::read_html")
  xml2::read_html(x, ..., encoding = encoding)
}
```

**Comment by jimhester** [comment]
The intent is for you to use `xml2::read_html()` directly.

**Comment by Fredo-XVII** [comment]
Hi Jim,

If that is the case, then maybe the pkgdown site should be changed to reflect that.  It is confusing when you see the documentation below, which confllicts with your statement above.  I am not invested either way, but would like for some clarity going forward.

website: https://rvest.tidyverse.org/

```
...

Key functions
The most important functions in rvest are:

Create an html document from a url, a file on disk or a string containing html with read_html().

...
```
