### ISSUE TITLE
gt package: A possibility to improve the html_table function?

### ISSUE THREAD

**Issue by georgevbsantiago** [tidyverse/rvest#268]
I saw the launch of the [`gt` package](https://blog.rstudio.com/2020/04/08/great-looking-tables-gt-0-2/). This provoked a reflection:

Is it possible to use the idea of the `gt` package to reverse engineer and, with that, improve the `html_table` function so that we can extract different types of tables in html?

Or is it not time to incorporate the `html_table` function into the `xml2` package and allow it to evolve?

The `html_table` function has some [(7 - new and old) issues open](https://github.com/tidyverse/rvest/issues?q=is%3Aissue+is%3Aopen+label%3A%22table+%F0%9F%8F%93%22), still unsolved.

Just a few thoughts. However, we cannot fail to recognize and thank you for the creation and development of the `rvest` package

**Comment by hadley** [comment]
I don't think insights from gt would be helpful for rvest — it's just such a totally different domain.
