### ISSUE TITLE
html_nodes(xpath) & html_table() does not work

### ISSUE THREAD

**Issue by cungbac** [tidyverse/rvest#269]
I used html_table to read from html_nodes(xpath) but it results a list without anything.

This is the sample:
url <- "http://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_population"
population <- url %>%
  read_html() %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/table[1]') %>% 
  html_table()

(source: https://www.r-bloggers.com/using-rvest-to-scrape-an-html-table/)

Then I tried:
population <- population[[1]]

Result: 'subscript out of bounds'

Please check.
Many thanks

**Comment by lifesabirch** [comment]
that xpath is out of date. If you use chrome to search for this xpath you get an empty array

$x('//*[@id="mw-content-text"]/table')

**Comment by cungbac** [comment]
> that xpath is out of date. If you use chrome to search for this xpath you get an empty array
> 
> $x('//*[@id="mw-content-text"]/table')

Thank you very much for your advice.
I just got the updated xpath, it works well.

**Comment by dmi3kno** [comment]
If this question is resolved, could you folks consider closing the issue
