### ISSUE TITLE
New feature: Convert nodeset with varying number of attributes to a dataframe

### ISSUE THREAD

**Issue by dmi3kno** [tidyverse/rvest#272]
I would like to contribute a function which I often use for extracting text and varying number of attributes from a nodeset.

Lets say we are interested in extracting a table to behavioral biases from wikipedia
```r
library(polite)
library(rvest)

bow("https://en.wikipedia.org/wiki/List_of_cognitive_biases") %>%
 scrape() %>%
 html_nodes("tr td:nth-child(1) a") 
#> {xml_nodeset (181)}
#>  [1] <a href="/wiki/Agent_detection" title="Agent detection">Agent detection</a>
#>  [2] <a href="/wiki/Ambiguity_effect" title="Ambiguity effect">Ambiguity effect</a>
#>  [3] <a href="/wiki/Anchoring" class="mw-redirect" title="Anchoring">Anchoring</a>
#>  [4] <a href="/wiki/Anthropocentric_thinking" class="mw-redirect" title="Anthropocentric thinking">Anthropocentric thinking</a>
```
As you can see from the first few examples, this nodeset contains some text, as well as a few attributes, but the number of attributes is changing from item to item. All of them have `href` and `title` attribute, but some also have `class`. It would take several iterations to:
a) find out all possible attributes the nodes may have in this nodelist (especially if some of them are rare
b) extract each attribute separately along with text
c) organize everything into a tidy format.

The function I would like to contribute is called `html_attrs_dfr()` because it is resembling  `httr_attrs()`, but returns them as a dataframe in a manner similar to  `purr::map_dfr()`.
```r
html_attrs_dfr(
  x,
  attrs = NULL,
  trim = FALSE,
  defaults = NA_character_,
  add_text = TRUE
)
```
The function basically iterates over attributes and nodeset and sweeps everything, including original text into a dataframe of the following format:
```r
#>   href                           title                    class       .text                   
#>   <chr>                          <chr>                    <chr>       <chr>                   
#> 1 /wiki/Agent_detection          Agent detection          NA          Agent detection         
#> 2 /wiki/Ambiguity_effect         Ambiguity effect         NA          Ambiguity effect        
#> 3 /wiki/Anchoring                Anchoring                mw-redirect Anchoring               
#> 4 /wiki/Anthropocentric_thinking Anthropocentric thinking mw-redirect Anthropocentric thinking
``` 
No dependencies other than `rvest` itself. Let me know if this is helpful. PR is coming. I appreciate quick merge, so that I can drop it from my package (on CRAN now) and remove dependency on `rvest`.

**Comment by hadley** [comment]
I'm not 100% sure this needs it's own helper, given that it's fairly simple with purrr:

``` r
library(rvest)
#> Loading required package: xml2

url <- "https://en.wikipedia.org/wiki/List_of_cognitive_biases"
html <- read_html(url)

nodes <- html_nodes(html, "tr td:nth-child(1) a") 
nodes %>% html_attrs() %>% purrr::map_df(tibble::as_tibble_row)
#> # A tibble: 186 x 3
#>    href                                          title                 class    
#>    <chr>                                         <chr>                 <chr>    
#>  1 /wiki/Agent_detection                         Agent detection       <NA>     
#>  2 /wiki/Ambiguity_effect                        Ambiguity effect      <NA>     
#>  3 /wiki/Anchoring                               Anchoring             mw-redir…
#>  4 /wiki/Anthropocentric_thinking                Anthropocentric thin… mw-redir…
#>  5 /wiki/Anthropomorphism#Psychology_of_Anthrop… Anthropomorphism      <NA>     
#>  6 /wiki/Attentional_bias                        Attentional bias      <NA>     
#>  7 /wiki/Attribute_substitution                  Attribute substituti… <NA>     
#>  8 /wiki/Automation_bias                         Automation bias       <NA>     
#>  9 /wiki/Availability_heuristic                  Availability heurist… <NA>     
#> 10 /wiki/Backfire_effect                         Backfire effect       mw-redir…
#> # … with 176 more rows
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by dmi3kno** [comment]
There are several drawbacks of using your method:
1) `html_attrs()` will skip over the nodes containing no attributes. If the same node contains text, it would be difficult to match the text (recovered with `html_text()`, I presume) to the row in the resulting data.frame (which should end up having a value in column `.text` and `NA`s in all other columns). At the very least you need to do `lapply(html_attr)` to make sure you return the same number of rows.
2) In order to recover both the text and the attributes, if any, you need to break the pipe and perform recovery of text, attributes and then perform some sort of join (or more likely `bind_columns()`). I would like to be able to recover everything from the list of nodes in a single run (i.e. in a pipe), making sure that no information from the `xml_nodeset` is lost.
3) My method does not require the dependency on `purrr` (and therefore is not affected by namespace clashes, between the packages).

I must admit I did not think of using `tibble::as_tibble_row()`. This beauty is so underrated!

**Comment by hadley** [comment]
1. This sounds like a bug in `html_attrs()` — the length of the output should always be the same as the length as the input.
2. That doesn't seem like a major concern to me.
3. What namespace clashes?

**Comment by dmi3kno** [comment]
1) Happy to validate and file the issue on `html_attrs()` and, possibly, other functions skipping the nodes. 
2) :(
3) Namespace clash:
```r
library(rvest)
library(purrr)
#> Attaching package: ‘purrr’
#> The following object is masked from ‘package:rvest’:
#>  pluck
```

**Comment by hadley** [comment]
Oh #209; I'd prefer to fix that.

**Comment by dmi3kno** [comment]
Thank you for this. Closing down the issue and calling back the PR.
