### ISSUE TITLE
Submit_form (and submit_request) need to be extended for modern forms

### ISSUE THREAD

**Issue by dmi3kno** [tidyverse/rvest#277]
Modern forms (even those provided in package function examples) no longer use simple elements, anticipated by `rvest` (input, select, textarea, button).

[This GoogleForm](https://docs.google.com/forms/d/1M9B8DsYNFyDjpwSK6ur_bZf8Rv_04ma3rmaaBiveoUI/viewform?edit_requested=true) used in examples contains only one "textarea", but radiobuttons are entirely written using `div` . 

Submit button is also entirely consisting of `div` and `span` tags and all identification is done via classes or a new attribute "role". 
![Screenshot from 2020-06-05 09-47-53](https://user-images.githubusercontent.com/13419011/83850898-d8b14400-a711-11ea-8648-66fc2dd9b887.png)
Because of it, `submit_form()` (actually `submit_request()` underneath it) fails.
```r
library(rvest)
test <- google_form("1M9B8DsYNFyDjpwSK6ur_bZf8Rv_04ma3rmaaBiveoUI")
f0 <- html_form(test)[[1]]
f1 <- set_values(f0, entry.564397473 = "abc")
submit_form(test, f1)
#>  Error: Could not find possible submission target. 
```
Could parsing of fields and parsing of buttons be extended to identify the elements by class or arbitrary attribute?

**Comment by hadley** [comment]
I don't think there's much that rvest can do here — these are not "modern" forms but non-semantic forms. If a form doesn't use html5 and instead hand implements using js, there is too much potential variation for rvest to handle.
