### ISSUE TITLE
rvest xml_nodeset returning n/a

### ISSUE THREAD

**Issue by Osc2wall** [tidyverse/rvest#279]
Hello. I am trying to retrieve the last updated date element of the following website [longpaddock](https://www.longpaddock.qld.gov.au/aussiegrass/). The copied HTML looks like this...
```<span id="map-gif-last-updated">21 June 2020</span>```
... however my result returns ```n/a``` instead of the date as below. Any ideas? Thank you in advance

``` r
library(rvest)
#> Loading required package: xml2
library(tidyverse)

webpage = read_html("https://www.longpaddock.qld.gov.au/aussiegrass/")
print(webpage)
#> {html_document}
#> <html lang="en">
#> [1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
#> [2] <body>\n\t\t<nav class="navbar-default navbar-static-top nav-upper"><div  ...
results <- webpage %>% html_nodes("#map-gif-last-updated")
results
#> {xml_nodeset (1)}
#> [1] <span id="map-gif-last-updated">n/a</span>
```

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
```

**Comment by hadley** [comment]
It looks like the HTML is updated via javascript, so unfortunately you'll need a different approach.
