### ISSUE TITLE
rvest returns “ ” instead of a number

### ISSUE THREAD

**Issue by ahaseemkunjucl** [tidyverse/rvest#280]
Hello, 

Here is my problem:

I am trying to scrape a number from the URL https://water.weather.gov/ahps2/hydrograph.php?wfo=rnk&gage=abbv2.

Using rvest, xml2, and tidyverse packages, and executing the codes below retrieves what I need but shows "" in places where there are numbers "0" and "1352":

> url <- 'https://water.weather.gov/ahps2/hydrograph.php?wfo=rnk&gage=abbv2'
> gage_dat <- read_html(url) %>% html_nodes("area")
> #gage_dat
> gage_dat[[14]]
{html_node}
<area shape="rect" coords="0,449,266,469" href="javascript:void( 0 )" alt="ABBV2(plotting HGIRR) " gage="" datum:="" title="ABBV2(plotting HGIRR) ">
> 

The element copied off Chrome "Inspect" is:

<area shape="rect" coords="0,449,266,469" href="javascript:void( 0 )" alt="ABBV2(plotting HGIRR) " gage="" 0"="" datum:="" 1352'"="" title="ABBV2(plotting HGIRR) ">

Why rvest is failing to scrape the numbers here?

Thanks for looking into this.

**Comment by hadley** [comment]
Probably because they're manipulated with javascript, which unfortunately rvest doesn't know anything about.
