### ISSUE TITLE
rvest CRAN

### ISSUE THREAD

**Issue by DiegoKoz** [tidyverse/rvest#281]
Hi,

I received an email saying rvest is going to be archived from CRAN. As my package has strong dependences with rvest, I need to know if there is any plans to keep rvest in CRAN or if I should move to another package that is going to replace it.

Thanks!

**Comment by dmi3kno** [comment]
Related to #277 .Hope @hadley and the team can turn it around quickly.

**Comment by daattali** [comment]
It's such a shame that CRAN has to email all of us (without using bcc...) and put us all on edge instead of resolving it directly with @hadley . I hope they give him enough time to fix whatever it is they want fixed and realize he might not be able to adhere to their normal short turnaround

**Comment by hrbrmstr** [comment]
@hadley you want a PR for this? It seems Google Forms changed the way it identifies fields.

**Comment by hrbrmstr** [comment]
Ah, it looks like someone already has https://github.com/tidyverse/rvest/pull/282

**Comment by hadley** [comment]
CRAN 🙄. I was already planning on submitting a fix today.
