### ISSUE TITLE
Re-licensing rvest

### ISSUE THREAD

**Issue by hadley** [tidyverse/rvest#287]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/tidyverse/rvest/graphs/contributors). @dholstius, @dmi3kno, @earino, @hmalmedal, @johncollins, @jrnold, @rentrop, @WilDoane, would you permit us to re-license rvest with the MIT license? If so, please comment "I agree" below.

* [x] [@dholstius](https://github.com/tidyverse/rvest/commits?author=dholstius)  
* [x] [@dmi3kno](https://github.com/tidyverse/rvest/commits?author=dmi3kno)  
* [x] [@earino](https://github.com/tidyverse/rvest/commits?author=earino)  
* [x] [@hmalmedal](https://github.com/tidyverse/rvest/commits?author=hmalmedal)  
* [x] [@johncollins](https://github.com/tidyverse/rvest/commits?author=johncollins)  
* [x] [@jrnold](https://github.com/tidyverse/rvest/commits?author=jrnold)  
* [x] [@rentrop](https://github.com/tidyverse/rvest/commits?author=rentrop)  
* [x] [@WilDoane](https://github.com/tidyverse/rvest/commits?author=WilDoane)

**Comment by dholstius** [comment]
I agree

**Comment by hmalmedal** [comment]
I agree

**Comment by johncollins** [comment]
I agree

- John

**Comment by dmi3kno** [comment]
I agree

**Comment by earino** [comment]
I agree

**Comment by WilDoane** [comment]
I agree
  
  

  
>

**Comment by dbuijs** [comment]
I agree.

**Comment by batpigandme** [comment]
Hi, @jrnold and @rentrop,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by rentrop** [comment]
I agree

**Comment by jrnold** [comment]
I agree
