### ISSUE TITLE
session_submit() fails on forms with relative action URL when base_url not set in html_form()

### ISSUE THREAD

**Issue by petrbouchal** [tidyverse/rvest#302]
On forms where the action parameter is specified as a relative URL, `session_submit()` returns an error when `base_url` is left unset in `html_form()`. This may also be the case with `html_form_submit()` but I have no easy way to check with my use case.

I believe this is a bug as specifying relative action URLs in forms seems to be standard practice. Also if I understand the `html_form()` documentation correctly, the stated behaviour is for the base URL to be inferred from the input HTML document:

> `base_url` Base url of underlying HTML document. The default, NULL, uses the url of the HTML document underlying x.

I understand this can be handled by setting `base_url` but that seems superfluous if the base URL is already contained in the rvest_session object passed (as per the documentation), and it requires passing around another parameter in modular/functional workflows.

I have been using the dev version over the past few weeks and believe this behaviour was not present in rvest at 5011ce93a77db041e5c84ac7f6c8697c9e04e930. (The chance that the code on the webpage changed is quite small.)

Reprex:

``` r
library(rvest)
library(rlang)

# Get page and form -------------------------------------------------------

url <- "http://stistko.uiv.cz/registr/vybskolrn.asp"
page <- session(url)
form <- html_form(page %>% rvest::read_html())
form[[1]]$action
#> [1] "skolyrn.asp"
form <- html_form(page) # passing an rvest_session object seems OK despite doc...
form[[1]]$action
#> [1] "skolyrn.asp"
form_baseurl <- html_form(page, base_url = url)
form_baseurl[[1]]$action
#> [1] "http://stistko.uiv.cz/registr/skolyrn.asp"

# params to be set as form has no defaults set
params <- c(uzemi = "CZ0514", # to narrow down search
            # default empty-type value for the rest:
            zrizovatel = "NIC", organ = "NIC", typ = "NIC", jazs = "NIC",
            delka = "NIC", forma = "NIC", jazob = "NIC", skupobor = "NIC", 
            kmobor = "NIC", obor = "NIC")

# Fill form ---------------------------------------------------------------

form_filled <- html_form_set(form, !!!params)
#> Error: `form` must be produced by html_form()

form_1_relurl_filled <- html_form_set(form[[1]], !!!params)

form_1_baseurl_filled <- html_form_set(form_baseurl[[1]], !!!params)

# Submit ------------------------------------------------------------------

results_relurl <- session_submit(page, form_1_relurl_filled, "XX")
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: skolyrn.asp
results_baseurl <- session_submit(page, form_1_baseurl_filled, "XX")

# Check that form worked and produces identical results -------------------

results_baseurl %>% read_html() %>% 
  html_element("body table:nth-of-type(2)") %>% 
  html_table(header = T)
#> # A tibble: 34 x 12
#>    ``    ``    ``    ``    ``    Č.p.  Č.or. `Část obce` ``    PSČ   ``    ``   
#>    <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>       <chr> <chr> <chr> <lgl>
#>  1 IZO   IZO   Typ   Škol… Ulice Č.p.  "Č.o… Část obce   Místo PSČ   ""    NA   
#>  2 6000… 0085… 7     Gymn… Jana… 804   ""    Turnov      Turn… 51101 "CZ0… NA   
#>  3 1024… 1024… C00   Stře… Jana… 804   ""    Turnov      Turn… 51101 ""    NA   
#>  4 1028… 1028… L11   Škol… Jana… 804   ""    Turnov      Turn… 51101 ""    NA   
#>  5 6000… 0085… 7     SUPŠ… Skál… 1603  ""    Turnov      Turn… 51101 "CZ0… NA   
#>  6 1024… 1024… C00   Stře… Skál… 373   ""    Turnov      Turn… 51101 ""    NA   
#>  7 1500… 1500… E00   Vyšš… Skál… 1603  ""    Turnov      Turn… 51101 ""    NA   
#>  8 1080… 1080… H22   Domo… Skál… 1603  ""    Turnov      Turn… 51101 ""    NA   
#>  9 6000… 0085… 7     Gymn… Nad … 574   ""    Semily      Semi… 51301 "CZ0… NA   
#> 10 1024… 1024… C00   Stře… Nad … 574   ""    Semily      Semi… 51301 ""    NA   
#> # … with 24 more rows
```

<sup>Created on 2021-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

[edited, remaining bits filed as separate issues]

**Comment by hadley** [comment]
I know exactly what introduced this problem — a mistaken assumption on my part. 

Can you please file separate problems as separate issues? That makes it easier for me to track and respond to them individually.

**Comment by petrbouchal** [comment]
Done.

Incidentally, when building the reprex for #305 I noticed that when the input into `html_form()` does not arrive via `session()`, the action field in the form is an absolute URL - in case this is helpful

``` r
library(rvest)

url <- "http://stistko.uiv.cz/registr/vybskolrn.asp"
page <- session(url)
form_a <- html_form(page)
form_a[[1]]$action
#> [1] "skolyrn.asp"
form_b <- html_form(page %>% read_html())
form_b[[1]]$action
#> [1] "skolyrn.asp"
form_c <- html_form(read_html(url))
form_c[[1]]$action
#> [1] "http://stistko.uiv.cz/registr/skolyrn.asp"
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
``` r
library(rvest)

page <- session("http://stistko.uiv.cz/registr/vybskolrn.asp")
form <- html_form(page)[[1]]
form$action
#> [1] "http://stistko.uiv.cz/registr/skolyrn.asp"
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
Thanks for catching all these issues!
