### ISSUE TITLE
html_text includes <style> content

### ISSUE THREAD

**Issue by geotheory** [tidyverse/rvest#303]
Should the contents of style tags be included in the output of an `html_text() call` - e.g. `p{color: red;}` in this example?

```r
require(rvest)
#> Loading required package: rvest
#> Loading required package: xml2
require(xml2)

h0 = '<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <title>html_text test</title>
  <style>
    p{color: red;}
  </style>
</head>
<body>
<h1>page title</h1>
<p>bla bla bla</p>
</body>
</html>'

h1 = xml2::read_html(h0)
html_text(h1)
#> [1] "html_text test\n    p{color: red;}\n  \npage title\nbla bla bla\n"
```

**Comment by geotheory** [comment]
Workaround:

    h1 %>% html_nodes('*>:not(style)') %>% html_text() %>% paste(collapse = '\n')

**Comment by hadley** [comment]
Hmmm, probably not because the contents of the `<style>` tag are never shown to the user in a browser.

**Comment by hadley** [comment]
But you should be using `html_text2()` here

**Comment by hadley** [comment]
And `html_text2()` already handles this case 😄
