### ISSUE TITLE
html_elements

### ISSUE THREAD

**Issue by kjschaudt** [tidyverse/rvest#307]
Testing rvest using the example at https://rvest.tidyverse.org/articles/rvest.html.  Anything calling html_elements fails and returns the message " could not find function "html_elements".  The example from your website is inserted below.

---

Brief description of the problem

```r
# insert reprex here
html %>% html_element("h1")
#> {html_node}
#> <h1>
html %>% html_elements("p")
#> {xml_nodeset (2)}
#> [1] <p id="first">This is a paragraph</p>
#> [2] <p class="important">This is an important paragraph</p>
html %>% html_elements(".important")
#> {xml_nodeset (1)}
#> [1] <p class="important">This is an important paragraph</p>
html %>% html_elements("#first")
#> {xml_nodeset (1)}
#> [1] <p id="first">This is a paragraph</p>

```

**Comment by hadley** [comment]
You'll need the dev version until rvest 1.0.0 is released to CRAN on March 1.
