### ISSUE TITLE
Flagging missing values in RVEST Output | Web Scrapping

### ISSUE THREAD

**Issue by PritishDsouza** [tidyverse/rvest#308]
Hi Team,

I am trying to scrape the **brand names** (_highlighted with yellow background in the image_) and **product titles** (_enclosed within orange colored box in the image_)

Now, as you can observe the second listing in the image does not have a brand but it has title (_U S Tex Printed Fashion Lycra Blend Saree (Maroon)_)

When I put together the final output I have 32 rows for titles and 30 rows for brand names, and I am unable to figure out the titles against which the brands are missing

Is it possible to introduce NA values in case the element is missing (e.g. brand name in this case)? Or Could you suggest a workaround this issue?

Warm Regards,
Pritish

![image](https://user-images.githubusercontent.com/48889764/105623467-eaca2900-5e3f-11eb-8323-2b8cc2c8f5f0.png)

```r
library(magrittr)

URL <- "https://paytmmall.com/shop/search?q=sarees&from=organic&child_site_id=6&site_id=2&category=5242&page=1&price=229%2C499&oq=sarees%20under%20500"

titles <-
  httr::GET(URL) %>%
  xml2::read_html(as = "text") %>%
  rvest::html_nodes(".UGUy") %>%
  base::as.character() %>%
  base::data.frame()

brand <-
  httr::GET(URL) %>%
  xml2::read_html(as = "text") %>%
  rvest::html_nodes("._3s55") %>%
  base::as.character() %>%
  base::data.frame()

DF <- cbind(titles, brand)

# Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 32, 30
```

**Comment by hadley** [comment]
You'll need to find the parent element that contains both title and brand, and then use `html_element()` on it: see for more details https://rvest.tidyverse.org/articles/rvest.html#element-vs-elements-1

(but note that `html_element()` only exists in the development version; you can substitute with `html_node()`/`html_nodes()` to work with the CRAN release)
