### ISSUE TITLE
html_elements() is missing

### ISSUE THREAD

**Issue by NicolasRuth** [tidyverse/rvest#309]
It seems the html_element() and html_elements() are not existing. I am using version 0.3.6. I tried the dev version from github 0.99.099(??) but it says it is corrupted. Where can I find the functions?

```r
starwars <- read_html("https://rvest.tidyverse.org/articles/starwars.html")
films <- starwars %>% html_elements("section")
```
"could not find function "html_elements"

**Comment by hadley** [comment]
They're only available in the development version. You can use `html_node()` and `html_nodes()` instead if you can't get the dev version installed.
