### ISSUE TITLE
Error when no matching nodes

### ISSUE THREAD

**Issue by hadley** [tidyverse/rvest#31]
``` R
library("rvest")

myhtml <- html("http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE21610")
myhtml %>% 
  html_nodes("tr:nth-child(23) .eye-protector-processed a")
```

**Comment by wqr786** [comment]
I think the html_nodes() should return a NULL value in case if a value doesn't exist.

I see @hadley committed and closed the issue. But I'm trying it out and it doesn't seem to work for me. I am trying to fetch some values from pages and for one of the page it is giving this error:
L::xmlValue, ..., .type = character(1)) : 
  Unknown input of class: NULL

Anyone know of this?

**Comment by hrbrmstr** [comment]
Can you post an example?

**Comment by hadley** [comment]
Please file a reproducible example as a new issue
