### ISSUE TITLE
parse html table with < symbol

### ISSUE THREAD

**Issue by kevin199011** [tidyverse/rvest#315]
Hi I'm trying to use the html_table to parse a table, like below test example. However, the < symbol was coded raw, instead of &lt; in the html file. This caused that the cell with < is missing. Is there any way to get around this issue? I attached a example to illustrate the issue. Thank you!

1 | A | 0.025
2 | B | <.0001
3 | C | 0.025

```r
x <- read_html("test.html")
tbls.node <- html_nodes(x, "table")
tbls <- html_table(tbls.node, fill = TRUE) %>% 
    as.data.frame()
```

[test.zip](https://github.com/tidyverse/rvest/files/6034197/test.zip)

**Comment by hadley** [comment]
No, sorry, that's invalid HTML so rvest can't even load it.
