### ISSUE TITLE
Empty tables break html_table()

### ISSUE THREAD

**Issue by epiben** [tidyverse/rvest#324]
Granted, empty tables are a bit weird but in a use case of mine, some pages contain empty tables that make the whole pipeline break. 

The following two both fail because `fill_table()` doesn't check if there are any cells which makes the call to `matrix()` in l. 238 fail. Fixing just `fill_table()` (e.g. around line 161) doesn't suffice, though, as `html_table()` itself also assumes there be come rows in the resulting tibble. So, my proposal is to simply return an empty tibble early in `html_table()` if the table is empty. 

```r
minimal_html("<table><tbody></tbody></table>") %>% 
  html_table()

minimal_html("<table></table>") %>% 
  html_table()
```

Again (#322), as instructed in the *Contributing guidelines* I'm just opening this as an issue to begin with but do offer a solution (this time accompanied by a test): https://github.com/epiben/rvest/commit/2912946b5a10f0d6f51cb04225e678687e84e3c7.

**Comment by hadley** [comment]
The point of asking first is to save you the time implementing something that we turn out not to want. For these simple cases, you can just go directly to a PR.

**Comment by epiben** [comment]
Good point; will do onward. Will make a PR shortly.
