### ISSUE TITLE
Feature Proposition: Select nodes using regex of its html_text()

### ISSUE THREAD

**Issue by m-g-h** [tidyverse/rvest#328]
I use rvests node selection features extensively, but lack one specific tool: *selecting a node by its text content*, similar to `find` from `BeautifulSoup` in python.

 Therefore I crafted my own little selection functions using `stringr::str_which` in conjunction with `html_text`, as can be seen in the reprex:

``` r
library(rvest)
#> Warning: Paket 'rvest' wurde unter R Version 4.0.5 erstellt
library(stringr)

## Example html
site <- read_html("https://rvest.tidyverse.org/articles/starwars.html")

## Nodes from which to select:
site %>%
    html_nodes("section > h2")
#> {xml_nodeset (7)}
#> [1] <h2 data-id="1">\nThe Phantom Menace\n</h2>
#> [2] <h2 data-id="2">\nAttack of the Clones\n</h2>
#> [3] <h2 data-id="3">\nRevenge of the Sith\n</h2>
#> [4] <h2 data-id="4">\nA New Hope\n</h2>
#> [5] <h2 data-id="5">\nThe Empire Strikes Back\n</h2>
#> [6] <h2 data-id="6">\nReturn of the Jedi\n</h2>
#> [7] <h2 data-id="7">\nThe Force Awakens\n</h2>

## Finding the position of the node:

node_which <- function(nodes, regex) {
    str_which(html_text(nodes), regex)
}

site %>%
    html_nodes("section > h2") %>% 
    node_which("New Hope")
#> [1] 4

## Selection a node by regex:

html_find <- function(nodes, regex) {
    nodes[node_which(nodes, regex)]
}

site %>%
    html_nodes("section > h2") %>% 
    html_find("New Hope")
#> {xml_nodeset (1)}
#> [1] <h2 data-id="4">\nA New Hope\n</h2>
```

<sup>Created on 2021-08-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Now i can select nodes by their text or find their position. Perhaps a similar functionality (crafted more professionally) could add to the already great functionality of `rvest`

**Comment by hadley** [comment]
I think I'd prefer to keep rvest scoped tightly around css/xpath selectors; I do expect folks to do their own post-scraping manipulation in R, just as you have done.
