### ISSUE TITLE
Help with agecheck

### ISSUE THREAD

**Issue by giuliogcantone** [tidyverse/rvest#329]
Hello, I'd like to scrape a url like this:

https://store.steampowered.com/224960/

The page requires an agecheck. What happens is that the scraper is redirected to:

https://store.steampowered.com/agecheck/app/224960/

instead than

https://store.steampowered.com/app/224960/

Can rvest handle the agecheck and access to the page html?

Thank You.

**Comment by hadley** [comment]
Possibly, via the `session` object.
