### ISSUE TITLE
Testing if two urls take me to the same webpage

### ISSUE THREAD

**Issue by datawranglingUCSBecon** [tidyverse/rvest#331]
Hello,

I'm interested in testing if two URLs take me to the same webpage. Below, I have two examples. The first is the link to my academic webpage and the second is a bit.ly to my webpage. I know that with bit.ly you can easily see the full URL. However, I've run into some issues where I have things like `https://site.com/user1` and `https://site.com/fex2904` that both take me to the same page. My first attempt using my constructed toy example is:

```{r}
read_html("https://sites.google.com/view/dannyklinenberg/home")==read_html("https://bit.ly/3DeZJRD")
```

but this returns an error. Any ideas? Thanks!

**Comment by hadley** [comment]
I'd suggest using httr for this:

``` r
httr::HEAD("https://sites.google.com/view/dannyklinenberg/home")$url
#> [1] "https://sites.google.com/view/dannyklinenberg/home"
httr::HEAD("https://bit.ly/3DeZJRD")$url
#> [1] "https://sites.google.com/view/dannyklinenberg/home"
```

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
