### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by kjschaudt** [tidyverse/rvest#337]
Apparently due to the expiration of the Lets Encrypt certificates, I am having problems with read_html (and the various curl functions).
 
For the target page, read_html is returning the following error.   "Error in open.connection(x, "rb") : 
  SSL certificate problem: certificate has expireda certificate error".  

So far, I have had no luck getting the sysop to update the certificates at their end.  Web searches suggested overriding  the security checks bu using set_config(config(ssl_verifypeer = 0L)).  That failed.

Do you have any suggestions?

Best regards
Ken Schaudt

```r
  library(httr)
Targetpage = "http://erddap.gcoos.org/erddap/tabledap/wmo_42932.htmlTable?time%2Clatitude%2Clongitude%2Cdepth%2Csea_water_speed_0%2Csea_water_direction_0&time%3E=2021-10-02T00%3A00%3A00UTC&time%3C=2021-10-04T13%3A24%3A00UTC"
 
 read_html(Targetpage)
```

**Comment by hadley** [comment]
You'll need to do something like this:

```R
library(httr)

url <- "http://erddap.gcoos.org/erddap/tabledap/wmo_42932.htmlTable?time%2Clatitude%2Clongitude%2Cdepth%2Csea_water_speed_0%2Csea_water_direction_0&time%3E=2021-10-02T00%3A00%3A00UTC&time%3C=2021-10-04T13%3A24%3A00UTC"
 
path <- tempfile()
httr::GET(url, write_disk(path), config(ssl_verifypeer = 0L))

rvest::read_html(path)
```

**Comment by kjschaudt** [comment]
Hadley, thanks for the suggestion.  Don;t recall what worked.  Some of the problems that I encountered were eventually fixed by sysops and I found a way to  update the lets encrypt certificates without having to update from Mojave.
