### ISSUE TITLE
Allow list of html_document objects to be saved to disk

### ISSUE THREAD

**Issue by jfunction** [tidyverse/rvest#344]
Sometimes a crash can occur or I will want to either come back to a project after a day or more. In these cases `polite` is going to lose any caching it may have done. As such, I tried saving my list of `html_document` objects, however this won't work. eg, saving one gives:
```R
resp <- rvest::read_html('https://www.google.com')
save(resp, file='resp')
load('resp')
resp
### Error in doc_type(x) : external pointer is not valid

str(rvest::read_html('https://www.google.com'))
### List of 2
###  $ node:<externalptr> 
###  $ doc :<externalptr> 
###  - attr(*, "class")= chr [1:2] "xml_document" "xml_node"
```
It seems these objects are [managed in C](https://github.com/r-lib/xml2/blob/main/src/xml2_doc.cpp#L212)? 

I'm not sure where to even ask about this - do I go down to the `xml2` folks, up to the `polite` repo, or ask here in the Goldilocks zone? Some kind of more persistent caching would be much appreciated, or maybe there is a simple solution to my usecase which I am missing?

**Comment by hadley** [comment]
This is a limitation with the way that R saves and loads object. You'll need to use `xml2::write_html()` instead.
