### ISSUE TITLE
read_html() error  

### ISSUE THREAD

**Issue by NTIF** [tidyverse/rvest#352]
when i use read_html(), some content can not be read. I exported the TXT and match the element.

The code 
    url<-'https://movie.douban.com/explore#!type=movie&tag=%E6%82%AC%E7%96%91&sort=rank&page_limit=20&page_start=0'
write(toString(web),"d:/1.txt")
I want to konw why and the how to do, thanks

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
