### ISSUE TITLE
Could not find function "html_structure"

### ISSUE THREAD

**Issue by GreatHandling14** [tidyverse/rvest#354]
Hi.
Got an issue while trying to use html_structure function, dont know how to solve this, error reads:

> html_structure(simpl_html)
Error in html_structure(simpl_html) : 
  could not find function "html_structure"

While R reads the prior function in creating an object simpl_html, doesnt go any further. Any help or suggestions will be appriciated
```r
# insert reprex here
```

**Comment by hadley** [comment]
That function comes from the xml2 package.
