### ISSUE TITLE
rvest problem when scraping tripadvisor

### ISSUE THREAD

**Issue by ivlassi** [tidyverse/rvest#356]
Hi,

I am trying to scrape tripadvisor reviews. I use the code

trip_ad <- read_html("http://www.tripadvisor.com/Hotel_Review-g189400-d10798588-Reviews-Electra_Metropolis_Athens-Athens_Attica.html")

house <- trip_ad  %>%
  html_elements("#REVIEWS .innerBubble")

But it returns a list of 0.
Could you help?

**Comment by hadley** [comment]
Tripadvisor is probably designed to avoid scraping in this way.
