### ISSUE TITLE
rvest and YouTube

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [tidyverse/rvest#359]
Hello rvest !

I searched for the term "youtube" in issues and no results.

My issue:

I was trying to use rvest to retrieve data from YouTube comment section, I used the Chrome InspectorGadget to find the correct `<tags>`  and kept getting empty characters. I even tried with the {ralger} package. The only thing I was able to get was some empty `<div>` tags. 

Upon further searching on scraping YouTube comment sections (all Python content showed up), it appears the only way to get such data is to use their Developer API.

My query:

_Is it possible to have a rvest  function that handles the YouTube developer API key that can parse the text?_

The YouTube data that gets returned is JSON, and the scrolling to fetch more comments requires a loop as 50 objects are returned in a single API call.

> I was curious if anyone else has tried to scrape YouTube for data using R. I know that Python has a library that as far as i have seen works only on Windows (i tried on Google Collab with failure).

Anyway, thanks for the great package. : )

**Comment by danlsn** [comment]
Hi @PythonCoderUnicorn, I'm not an rvest dev but have you looked into the package [soodoku/tuber?](https://github.com/soodoku/tuber)

You will probably need to obtain a (free?) api key to use YouTube's Developer API though.

From what I gather it deals with pagination for you so you don't have to worry about looping to fetch all comments!

Good luck!
