### ISSUE TITLE
unable to scrap a site which dynamically load web content through javascript

### ISSUE THREAD

**Issue by cregouby** [tidyverse/rvest#365]
As per twitter call for "scrapping javascript site" use-case, I'm trying to scrap values on sites like 
[chargeprice](https://www.chargeprice.app/?poi_id=43485&poi_source=going_electric)
and / or
[mobisdec](https://mobisdec.fr/#carte)
Both relies on leaflet or equivalent, that dynamically loads content through javascript query on-click on the map marker, 

First step is to extract leaflet markers URLs, where I would like `{rvest}` to help.  
Second step is to query those URLs, here forged API call may require more specific query forging...

**Comment by hadley** [comment]
This will be resolved by #245
