### ISSUE TITLE
Error with Scrapping Multiple Pages with ForLoop

### ISSUE THREAD

**Issue by emirizatrashid** [tidyverse/rvest#367]
Hi! I used a for loop to scrape multiple pages and I received an occasional error: 

Error in readBin(3L, "raw", 65536L) : 
  transfer closed with outstanding read data remaining

I tried running the code again and it worked, but sometimes run into the same error after 10-20 pages.  The longest stretch was running a loop for 600 pages (I thought the problem was over at this point) before encountering it again.

**Comment by hadley** [comment]
Unfortunately there's not much we can do without a reprex.
