### ISSUE TITLE
Github Actions Can't Install Dev Version

### ISSUE THREAD

**Issue by OlexiyPukhov** [tidyverse/rvest#394]
How would I use this in github actions? Trying to get the package two different ways, but they both fail with github actions. I can run it locally with no issue using install_dev(). 
I'm getting an error with > remotes::install_github("tidyverse/rvest")
Error: Error: Failed to install 'rvest' from GitHub: and an error with remotes::install_dev("rvest")
Error: Error: Failed to install 'unknown package' from GitHub:

![image](https://github.com/tidyverse/rvest/assets/98609419/2df61ce9-224f-4b1b-8f07-5e9011136fd0)
The url in the picture says:
cannot open URL 'https://api.github.com/repos/tidyverse/rvest/contents/DESCRIPTION?ref=HEAD'
![image](https://github.com/tidyverse/rvest/assets/98609419/56ce9c87-54ee-4397-8a48-19d52e9884ef)

Don't think the Github PAT is the issue here.

The relevant github actions code:

      - name: Install R packages
        run: |
          R -e 'install.packages("remotes", repos = "http://cran.rstudio.com")'
          R -e 'remotes::install_github("tidyverse/rvest")'

**Comment by hadley** [comment]
I suspect the failure is happening because the bundled PAT is getting rate limited. I haven't seen this sort of problem for a while, which I suspect is because I'm relying on https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies and generally `usethis::use_github_action()`, which does a bunch of work to setup your action in a way that's most likely to succeed.

**Comment by OlexiyPukhov** [comment]
I tried putting my PAT in, but it just gave me the same error: 

Error: Error: Failed to install 'rvest' from GitHub:
  can't convert package rvest with RemoteType 'any' to remote
Execution halted

**Comment by hadley** [comment]
Can you try using pak instead? That's what we now use for all our github actions.

**Comment by OlexiyPukhov** [comment]
Okay, I'm using pak and also downloading the most stable version with read html live. It downloads, but I get another error. Making a new issue.
