### ISSUE TITLE
read_html_live() memory "leak"

### ISSUE THREAD

**Issue by rdelrossi** [tidyverse/rvest#408]
I'm experimenting with read_html_live() using Vivaldi as the headless browser (I try to avoid installing Google Chrome). 

It works great. But, I've noticed that it's leaving some Chromate cruft behind. Each time I run my R script, the macOS activity monitor shows a new instance of the "Vivaldi Helper (Renderer)" that costs about 500 MB of memory and actually grows from there. Run the script too many times, and, naturally the whole computer grinds to a halt. When I force-kill the processes in the activity monitor, the R console report "[error] handle_read_frame error: websocketpp.transport:7 (End of File)"

I'm not sure if I'm missing some kind of clean-up step, or if this is a Vivaldi problem, of if this is an rvest bug, but wanted to let you know, @hadley.

_Later:_
I've noticed that pairing `payload <- rvest::read_html_live(url)` with `payload$session$close()` addresses the problem I'm describing (i.e., the "Vivaldi Helper (Renderer)" disappears from he Activity Monitor). Apologies if I missed the need for doing this in the docs.

**Comment by hadley** [comment]
If you `rm(payload)`, then the garbage collector should close down the process a bit later.

**Comment by rdelrossi** [comment]
I'll do that, thanks.

**Comment by hadley** [comment]
@rcepka can you provide any more details?

**Comment by hadley** [comment]
Closing this because without a reprex, unfortunately there's nothing I can do.
