### ISSUE TITLE
Example broken in LiveHTML page

### ISSUE THREAD

**Issue by brunomioto** [tidyverse/rvest#409]
The link used in [https://rvest.tidyverse.org/reference/LiveHTML.html](https://rvest.tidyverse.org/reference/LiveHTML.html) is broken

```r
library(rvest)

sess <- read_html_live("https://www.bodybuilding.com/exercises/finder")

Error: Chromote: timed out waiting for event Page.loadEventFired
```

![image](https://github.com/tidyverse/rvest/assets/10459392/0d118e04-bd85-4aac-962f-ca62f2b66bd9)

**Comment by r2evans** [comment]
That code worked for me, a subsequent `sess$view()` produces

![image](https://github.com/user-attachments/assets/c164dbe7-2e4e-4933-89b3-c7d78bcb4f30)

I'm not a dev, just somebody trying to learn more about the package.

**Comment by hadley** [comment]
Works for me, so maybe the site was just down temporarily.
