### ISSUE TITLE
Chrome v128 - Error in with_random_port():

### ISSUE THREAD

**Issue by OlexiyPukhov** [tidyverse/rvest#421]
Similar problem that another user is experiencing with chromote:

https://github.com/rstudio/chromote/issues/170

The error that I get with sess <- read_html_live(some_link_here)
is:
Error in with_random_port():
! Cannot find an available port. Please try again.
Caused by error in startup():
! Failed to start chrome. Error:

This is the same issue that the user in the linked thread has experienced. This is probably an issue with Chrome v128.

**Comment by alireza5969** [comment]
My problem too.

**Comment by OlexiyPukhov** [comment]
The new update to chromote fixed the issue.
